### ISSUE TITLE
creates a symlink named terraform

### ISSUE THREAD

**Issue by jsimoni** [warrensbox/tgswitch#104]
tgswitch creates a symlink named terraform that points the version of terragrunt I specify

**Comment by warrensbox** [comment]
FIxed with : #105

**Comment by warrensbox** [comment]
@jsimoni can you please confirm if this is working? 
Get the latest: https://warrensbox.github.io/tgswitch/additional

**Comment by jsimoni** [comment]
Yes, it does seem to be working now. Thanks.
