### ISSUE TITLE
Add .tgswitchrc support like on tfswitch

### ISSUE THREAD

**Issue by jcolfej** [warrensbox/tgswitch#55]
It's just an idea....

On tfswitch, there is a .tfswitchrc file that allows you to put a specific version of Terraform linked to your project.

Why not add the .tgswitchrc file on tgswitch?

**Comment by warrensbox** [comment]
This feature was added with MR #65.
Upgrade tgswitch to get the latest version. 
```ruby
brew upgrade warrensbox/tap/tgswitch
```

## Please test the latest release and let me know if there are any bugs.

### Use .tgswitchrc file
<img align="center" src="https://s3.us-east-2.amazonaws.com/kepler-images/warrensbox/tgswitch/manual-tgswitchrc.gif" alt="drawing" style="width: 480px;"/>

1. Create a `.tgswitchrc` file containing the desired version
2. For example, `echo "0.14.1" > .tgswitchrc` for version 0.14.1 of terragrunt
3. Run the command `tgswitch` in the same directory as your `.tgswitchrc`

**Automatically switch with bash**

Add the following to the end of your `~/.bashrc` file:
(Use `.tgswitchrc`)

```
cdtgswitch(){
  builtin cd "$@";
  cdir=$PWD;
  if [ -f "$cdir/.tgswitchrc" ]; then
    tgswitch
  fi
}
alias cd='cdtgswitch'
```

<img align="center" src="https://s3.us-east-2.amazonaws.com/kepler-images/warrensbox/tgswitch/auto-tgswitchrc.gif" alt="drawing" style="width: 480px;"/>

**Automatically switch with zsh**


Add the following to the end of your `~/.zshrc` file:

```
load-tgswitch() {
  local tgswitchrc_path=".tgswitchrc"

  if [ -f "$tgswitchrc_path" ]; then
    tgswitch
  fi
}
add-zsh-hook chpwd load-tgswitch
load-tgswitch
```
> NOTE: if you see an error like this: `command not found: add-zsh-hook`, then you might be on an older version of zsh (see below), or you simply need to load `add-zsh-hook` by adding this to your `.zshrc`:
>    ```
>    autoload -U add-zsh-hook
>    ```

*older version of zsh*
```
cd(){
  builtin cd "$@";
  cdir=$PWD;
  if [ -f "$cdir/.tgswitchrc" ]; then
    tgswitch
  fi
}
```

**Comment by jcolfej** [comment]
@warrensbox Thank you for this great feature! 
Auto switch using tgswitchrc file works for me ;)
