### ISSUE TITLE
inconsistently tgswitch command returned "Unable to get release from repo"

### ISSUE THREAD

**Issue by pulakiitr** [warrensbox/tgswitch#88]
```
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch --version

Version: 0.4.326
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$

~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ mkdir ~/tg-test

~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
Switched terragrunt to version "0.28.7" 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
Switched terragrunt to version "0.28.7" 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
Switched terragrunt to version "0.28.7" 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:22:45 Unable to get release from repo 
2021/09/09 21:22:45 Unable to make request Please try again.
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:22:48 Unable to make request Please try again.
2021/09/09 21:22:48 Unable to make request Please try again.
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:22:50 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:22:53 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:22:55 Unable to get release from repo 
2021/09/09 21:22:55 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:22:58 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:02 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:03 Unable to get release from repo 
2021/09/09 21:23:03 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:05 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:07 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:09 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:11 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:13 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:16 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:19 Unable to get release from repo 
2021/09/09 21:23:19 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:21 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:24 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:26 Unable to get release from repo 
2021/09/09 21:23:26 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:29 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:31 Unable to get release from repo 
2021/09/09 21:23:31 Unable to get release from repo 
2021/09/09 21:23:31 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ tgswitch -b ~/tg-test/terragrunt 0.28.7
2021/09/09 21:23:43 Unable to get release from repo 
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$ ll ~/tg-test/
total 0
drwxr-xr-x+ 84 xxxxxxxx  staff  2688 Sep  9 21:21 ..
lrwxr-xr-x   1 xxxxxxxx  staff    55 Sep  9 21:22 terragrunt -> /Users/xxxxxx/.terragrunt.versions/terragrunt_0.28.7
drwxr-xr-x   3 xxxxxxxx  staff    96 Sep  9 21:22 .
~/github/azure/az-AKS/modules/deploy_Kubernetes_pod$
```

**Comment by nadirollo** [comment]
Same problem here. Fails randomly

**Comment by mihica123** [comment]
Same here. Switched through a couple of versions, stopped working. 
Even after purging the PATH of the tgswitch executable and rerunning the install script.

**Comment by Vishwas1976** [comment]
same issue

**Comment by steven-edgar** [comment]
Also seeing this, I've tried tgswitch versions 0.4.326, 0.4.315 & 0.3.308. 
Hitting github directly, either to download a release or list releases, works fine, eg
`curl https://api.github.com/repos/gruntwork-io/terragrunt/releases/`
Similarly to other reporters I'm seeing this error whether or not I've already got the relevant version of Terragrunt in ~/.terragrunt.versions/
To me there are 2 bugs here, firstly tgswitch trying to (I think) list versions available on github even when the version requested is already available locally, and secondly the issue actually communicating with Github.

**Comment by steven-edgar** [comment]
I've created a fork of this project with fixes in, so that it only hits Github if the version requested doesn't already exist in ~/.terragrunt.versions/. I suspect the way the code is actually accessing github is generating too many requests, but that's beyond my abilities to fix, as I've not really dealt with Go before. Upstream may not want to take this change as-is, but it works for me. Clone it, install go (yum install epel-release && yum install golang), then run "make release". [https://github.com/steven-edgar/tgswitch](url). I've tested with switching between existing versions and downloading a new one, and using a .tgswitchrc file to specify the version, all using the '-b' flag to set the bin location as I don't have access to /usr/local/bin on this system, so haven't tested that.

**Comment by korenshoshan** [comment]
Same here.

**Comment by Ian-T-Price** [comment]
Thanks for your efforts @steven-edgar; I think you've hit the nail on the head.

I tried your code but it didn't work initially.  I then figured out that I was still rate limited at the time.  After that period lapsed it has worked well for me.

The link mentioned (https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) makes reference to a URL to check the API usage.  HOWEVER, that hits the API and uses up your quota! Doh!

**The quota is 60 requests per hour.**  There is a check that does not hit your API rate limit which can be found at: https://docs.github.com/en/rest/reference/search#rate-limit

 I've created an alias to put this into a useable format.  This probably ought to be a bash or zsh function but it works.  It does require [jq JSON parser](https://stedolan.github.io/jq/)
 
`alias tgsapi='echo -e "\nRemaining GitHub API requests: $(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/rate_limit | jq ".rate | .remaining")\n\t\t    Resets at: $(date -d @$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/rate_limit | jq ".rate | .reset"))"'`

```
$ tgsapi                                                                                                                                                                                                                                                                     

Remaining GitHub API requests: 59
		    Resets at: Tue  9 Nov 12:26:45 GMT 2021
```

**Comment by warrensbox** [comment]
@Ian-T-Price @korenshoshan @Vishwas1976 @mihica123 @pulakiitr @nadirollo 

Please get the latest version of tgswitch - Version: 0.5.378 #98 . See how to get latest [here](https://warrensbox.github.io/tgswitch/additional).
Please see the changelog here: https://github.com/warrensbox/tgswitch/blob/master/CHANGELOG.md
I am no longer using github APIs to get the releases. In the older tgswitch version - all users share the same API token (embedded in the app). Github limits the number of calls (used by this API token). Some tgswitch users were unable to switch when tgswitch hits the API limit. Although it worked, it was fundamentally flawed.

The new version of `tgswitch` gets at a list of the terragrunt version (periodically updates) from [here](https://warrensbox.github.io/terragunt-versions-list/index.json). Once the user selects a version, it should directly download from the gruntwork.io/terragrunt release page. The new version should work faster.

**Comment by Ian-T-Price** [comment]
This is working as described; my personal API count is unaffected by downloading different versions of terragrunt.

Many thanks for your time and effort to fix this issue; much appreciated.

I consider this issue closed

**Comment by davidjeddy** [comment]
Continue to see this with v 0.6.0 on a Debian Linux box.
