### ISSUE TITLE
Do not always call lib.GetAppList

### ISSUE THREAD

**Issue by grimm26** [warrensbox/tgswitch#90]
Always calling lib.GetAppList is unnecessary. We should first check if we already have that version downloaded. If so, use it. If not, then go through the routine of downloading the list and all that.

The way it is now generates a lot of unnecessary API calls to github and slows things down a lot.

**Comment by warrensbox** [comment]
You are right. I am working on fixing this.

**Comment by warrensbox** [comment]
Released with Version: 0.5.378
Thanks for contributing!
Also, please see the changelog here: https://github.com/warrensbox/tgswitch/blob/master/CHANGELOG.md
I am no longer using github APIs to get the releases. In the older tgswitch version - all users share the same API token (embedded in the app). Github limits the number of calls (used by this API token). Some tgswitch users were unable to switch when tgswitch hits the API limit. Although it worked, it was fundamentally flawed. 

The new version gets at a list of the terragrunt version (periodically updates) from [here](https://warrensbox.github.io/terragunt-versions-list/). Once the user selects a version, it should directly download from the gruntwork.io/terragrunt release page. The new version should work faster.

Your changes are still good and I've incorporated in this new version. Please download the latest version and let me know if you see any issues. Again, thank you for contributing.
